### ISSUE TITLE
We should have a user profile pagethat display user claims

### ISSUE THREAD

**Issue by annahj1006** [ITU-BDSA23-GROUP4/Chirp#103]
## User story
We want the user to have a page, where they can examine their own profile

## Precise description of what to do and evt. time estimate
Make the page, it should by start only contain a list of initial claims by the user

## Acceptance criteria (testeable)
The site should contain:
- [ ] Name of user
- [ ] List of their claims

**Comment by Lukan707** [comment]
This is dependent on issue #112
