### ISSUE TITLE
Unit test for getting Author by ID

### ISSUE THREAD

**Issue by annahj1006** [ITU-BDSA23-GROUP4/Chirp#105]
## User story
We should test the method for getting an author by ID

## Precise description of what to do and evt. time estimate
This should be done in the unit test script for the authorRepository. It should look like the already existing unit tests, using the in memory database

## Acceptance criteria (testeable)

- [x] A test that makes sure getting an author by the ID returns the correct author
- [x] A test that makes sure trying with a wrong ID won't return the expected author

**Comment by Lukan707** [comment]
Nice work
