### ISSUE TITLE
Find out the advanteges and disadvanteges of different autherization options

### ISSUE THREAD

**Issue by AlbinoLoaf** [ITU-BDSA23-GROUP4/Chirp#106]
## User story
As a developer, I want to limit who can access what parts of my web application and in doing so I want to know what the options provide in terms of limitations and functionality

## Precise description of what to do and maybe time estimate
Research Authentication and authorization options and provide advantages and disadvantages for each. 
Known options: 
- Easy Auth
- Entra ID B2C 
- Identity Core

## Acceptance criteria 
Decision chart of why we chose what and why not others

**Comment by annahj1006** [comment]
We've choosen Easy Auth
