### ISSUE TITLE
Adding a Chirp Form for logged in users

### ISSUE THREAD

**Issue by annahj1006** [ITU-BDSA23-GROUP4/Chirp#114]
## User story
We want to be able to write cheeps in the UI

## Precise description of what to do and evt. time estimate
Research what a Form is
Add a Chirp Form which is only visible when a user is logged in.
It should be its own page containing a headline "Message", informing the user where they are. Then a textarea where the user can input their message, and a publish button, which will add the cheep to our database.

## Acceptance criteria (testeable)
Only a logged in user should be able to add something to the Form
Should inform the user the message can be at most 160 characters.
Make sure the FluentValidation doesn't redirect the page, it should inform the user of whats happening
Make after Issue #113

**Comment by annahj1006** [comment]
Issue 113 closed with the form created and working. The only missing part of this issue, is to make it work on the webapplication itself, not running on anything locally.
This requires authentication to work completely

**Comment by Lukan707** [comment]
This is dependent on issue #122

**Comment by annahj1006** [comment]
Issue 122 is closed, so the only thing missing is having a working release that passes Helge's tests
