### ISSUE TITLE
Create a Hosted Azure SQL database

### ISSUE THREAD

**Issue by annahj1006** [ITU-BDSA23-GROUP4/Chirp#115]
## User story
We would like to have a SQL database on our Azure.
(Might need a better description)

## Precise description of what to do and evt. time estimate
See for example this guide: https://learn.microsoft.com/en-us/azure/azure-sql/database/single-database-create-quickstart?view=azuresql&tabs=azure-portal

**Comment by Lukan707** [comment]
A SQL Server database has been created with the name bdsagroup4-chirpdb
