### ISSUE TITLE
Setup Azure Active Directory B2C

### ISSUE THREAD

**Issue by Lukan707** [ITU-BDSA23-GROUP4/Chirp#123]
## User story
As a developer I want to setup Azure Active Directory B2C on Azure, which will act as the middleware, I will later tie the application to, to be able to use it for authentication and authorization.

## Precise description of what to do and evt. time estimate
Setup Azure Active Directory B2C on Azure.
This video can maybe be used as an guide:
https://www.youtube.com/watch?v=VfwtoP1Xurg&list=PLLWMQd6PeGY0cZFMqx5ijmdaD87sJKCsU&index=20 

## Acceptance criteria (testeable)
An active B2C tentant should run on Azure.

**Comment by Faberen** [comment]
B2C have been added, need to add code that interprets the token we receive now
