### ISSUE TITLE
As a developper I want to add a unfollow and follow cabability

### ISSUE THREAD

**Issue by annahj1006** [ITU-BDSA23-GROUP4/Chirp#166]
## User story
Users can follow any other user, except themselves. Initially, users do not follow any users. 

## Precise description of what to do
Any given user once Authenticated need to be able to access others user pages and follow them, so when they access their own private time line along with the chirps of those they follow.
This can be done in a few ways. The easiest way to do it is to create a set on a given author though this might create GDPR issues.
To avoid those issues make sure to use "information-less" values such as id.
To follow the front-end needs: to send the information back and update the database, and when the private timeline is loaded, the Database should return all the relevant cheeps as DTOs.

The button next to the username should show "follow" when the user doesn't follow them, and after they've followed, it should be changed to "unfollow", and vice verca

## Acceptance criteria (testeable)
Unit Tests:
- [x] The author should have a set, that contains whoever they are following.
- [x] The author should have a set, that contains whoever that are following them
- [x] Test that following a user will ad them to the following set.
- [x] Test at unfollow a user will remove them from the following set
- [x] Test that when someone follow you, the set is updated
- [x] Test that when someone unfollows you, the set is updated

UI Tests:
- [ ] This requires two methods, a unfollow and follow method, which will work with a button on a cheep display.
- [ ] There should be a toggle button beside the username to follow/unfollow except for the specific user that is logged in
- [ ] Test at when entering the userTimeline, that the cheeps of whom they are following appear with their own.

**Comment by AlbinoLoaf** [comment]
## Description 
Any given user once Authenticated need to be able to access others user pages and follow them so when they access their own private time line along with the chirps of those they follow. 
This can be done in a few ways. The easiest way to do it is to create a set on a given author though this might create GDPR issues. 
To avoid those issues make sure to use "information-less" values such as id.

**Comment by Lukan707** [comment]
This ressource is usefull to create the correct ef core relationship table:
https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many#self-referencing-many-to-many:~:text=ON%20DELETE%20RESTRICT)%3B-,Self%2Dreferencing%20many%2Dto%2Dmany,-The%20same%20entity

**Comment by Lukan707** [comment]
Edit to description requirements.
The follow/unfollow "button" next to the author of the cheep, should not be a toggle button, but a link, as per requiremnt:

https://github.com/itu-bdsa/lecture_notes/blob/main/sessions/session_11/README_PROJECT.md#:~:text=should%20contain%20a%20link%20next%20to%20all%20listed%20user%20names

**Comment by Lukan707** [comment]
The feauture has been implemented, and tested with Unit test.
Since Playwright have not been implemented, the UI tests have not been completed.

This should be done, but is dependent on issue: #167
