### ISSUE TITLE
UI Tests with PlayWright (should just be complete before end of project)

### ISSUE THREAD

**Issue by AlbinoLoaf** [ITU-BDSA23-GROUP4/Chirp#167]
## Description
We need to test that our  UI acts as we expect it to, and that it meets the testing criteria, that we are expecting automatically so we no longer need to test it manually during local development.
Using headless testing along with playwright.
Could be rather tricky to implement.

## Acceptance criteria (testable)
- [ ] That unfollow and follow are tested using the button on cheeps
- [ ] Sending cheeps are tested
- [ ] That loggin in is tested
- [ ] The UI tests should run on a chromium browser, Webkit and Mozilla to test it.

**Comment by Lukan707** [comment]
@Faberen would you please asses if the requirements of this issue have been resolved in your pull requests, and if so, link the pull request with this issue and close it.
