### ISSUE TITLE
As a developer I want to seperate concerns makin sure the CSV file reader is independent 

### ISSUE THREAD

**Issue by AlbinoLoaf** [ITU-BDSA23-GROUP4/Chirp#2]
## User story
Separating the concerns of the code and implementing a single concern principle for that part of the code to make it more readable and extensible without affecting other parts of the code. 
## Description 
This should be done first by refactoring the code and then implementing a library for the CVS parser thus increasing abstraction and readability. 
## Acceptance criteria
- The CVS file reader and writer parts of the code are independent and do not have facets in other parts of the code 
- Independence

## Definition of done
A library is implemented and it should be easily readable and well commented. 
## Depency 
This issue should be resolved previous to issue #3

**Comment by SkarpKat** [comment]
Issue has be resolved and merged.
