### ISSUE TITLE
Make it so the program does not make new database every run

### ISSUE THREAD

**Issue by SkarpKat** [ITU-BDSA23-GROUP4/Chirp#202]
## User story
As a developer and user I don't want the database to be refreshed. 

## Precise description of what to do and evt. time estimate
Make it so the database is not created every run

## Acceptance criteria (testeable)
Create database if not exist
Don't create if exist

**Comment by Lukan707** [comment]
This ressource might be helpfull, it suggests creating a method which returns a boolean.
The method uses a try catch statement, which tries to connect to the database, if it can, the method returns true, and otherwise returns false in the catch statement.
