### ISSUE TITLE
As a user I want to be able to like cheeps

### ISSUE THREAD

**Issue by SkarpKat** [ITU-BDSA23-GROUP4/Chirp#206]
## User story
As a user I want to be able to like cheeps and order cheeps by likes

## Precise description of what to do
Make it so the User is able to like a cheep, the User should also be able to rank the cheeps by the likes and return it to ordered by date.

## Acceptance criteria (testeable)
- An User can like a cheep
- A Cheep can have likes
- A Cheep can have multiple likes
- An User can like multiple cheeps

## Notes:

- [x] Give cheeps a like value
- [x] Give the author a tool to increase the like number
- [x] Make test for like function

**Comment by Lukan707** [comment]
The choosen implementation is very simple and somewhat naive.

A like attribute will be added to the cheep entity.
A like button on the razor page, will increase this counter using a method in cheeprepository.
This have the implications that:
- A user can like a cheep multiple times.
- A user can not remove their like
- It is not possible to see which user has liked a cheep, but only the amount of likes

**Comment by Lukan707** [comment]
Todo:
- Create a call to the IncreaseLikeAttributeInCheep form the Like button in razor pages.
- Test method with unit tests
