### ISSUE TITLE
Refactor the database to check for a csv file, and create it, if it does not exists

### ISSUE THREAD

**Issue by Lukan707** [ITU-BDSA23-GROUP4/Chirp#21]
As a user we want the program to create a csv file if it does not exists already. This is that users do not manually need to create a csv file, to run the program.

## Acceptance criterieas (Create tests to check theese criterias)
- The program should check if the file already exists, and create it, if it doen't.
- The program should not create and overwrite a file, that already exists.

**Comment by SkarpKat** [comment]
This has been completed and merged to development
