### ISSUE TITLE
As a developer i want to refactor the CSV database to a web service

### ISSUE THREAD

**Issue by annahj1006** [ITU-BDSA23-GROUP4/Chirp#22]
Implement two endpoints in your CSV database web service: /cheep and /cheeps. Sending a JSON object, e.g., of the form {"Author":"ropf","Message":"Hello, World!", "Timestamp": 1684229348} as the body of an HTTP POST request to the /cheep endpoint shall store the cheep in the remote database. An HTTP GET request to the /cheeps endpoint shall return all cheeps that are stored in the CSV database as a list of JSON objects.

This is a refactoring step. That is, reuse suitable code from your current SimpleDB library project and move its functionality behind the web interface described above.

**Comment by Lukan707** [comment]
Implemented on branch RefactorDatabaseToWebServiec_Anna
