### ISSUE TITLE
As a developer i want to refacter the Chirp project (client) to use the database web service without the localhost

### ISSUE THREAD

**Issue by annahj1006** [ITU-BDSA23-GROUP4/Chirp#23]
As developers we want the refactor our chirp cli client to save send data to the web service on localhost, rather than directly to the database. This prepares us to move the web api and database to a remote server (Azure).

## Acceptance criterias:
- The client (Chirp project) should use the http client to access the localhost on the correct port (determined when running the web api service), intead of the database project.
- When given the command "read" the client should use a get request to retrieve the data form the web api.
- When given the command "cheep" and a value, the client should use a post request to retrieve the data from the web api

**Comment by Lukan707** [comment]
Implemented in branch RefactorDatabaseToWebApi_Anna

**Comment by Lukan707** [comment]
Not implemented, as told by Teaching Assistents
