### ISSUE TITLE
Unit tests for remaining functionality that hasn't been tested

### ISSUE THREAD

**Issue by annahj1006** [ITU-BDSA23-GROUP4/Chirp#237]
## User story
We want our program to be tested correctly, so we need to make sure that all of our important functionalities are tested in one way or another. 

## Precise description of what to do and evt. time estimate
Make sure that the methods we use are all tested, if they're not being tested create a unit test to do this

Should be done before handin!

## Acceptance criteria (testeable)
The tests created should pass
Everthing that is of importance in the project should be tested at least once

**Comment by Lukan707** [comment]
@annahj1006 can you point out, or briefly describe what functionality we are missing test coverage on?

**Comment by annahj1006** [comment]
> @annahj1006 can you point out, or briefly describe what functionality we are missing test coverage on?

Its just an overall criteria that Helge gave, we should just make sure we're fullfilling it.
