### ISSUE TITLE
Make sure all warnings are dealth with

### ISSUE THREAD

**Issue by annahj1006** [ITU-BDSA23-GROUP4/Chirp#238]
## User story
We want the project to run clean, so in the final implementation there shouldn't be any warnings in the program.

## Precise description of what to do and evt. time estimate
Remove all warnings, that is, deal with them properly so the functionality is still the same

## Acceptance criteria (testeable)
There should be no warnings in the program

**Comment by Lukan707** [comment]
There are no warnings at the current state of the project
