### ISSUE TITLE
Pagination on "my timeline" does not work

### ISSUE THREAD

**Issue by Lukan707** [ITU-BDSA23-GROUP4/Chirp#250]
## User story
As a user I exepect to see all of my own cheeps, as well as all cheeps of thoose I follow on my timeline.

## How to reproduce
1. Follow user Jaqualine.
2. Verify that there are 12 pages on her public timeline
3. Check that there at least 12 pages on "my timline", which is the expected behavouir, but actual behavouir.

## Acceptance criteria (testeable)
When viewing my timeline, and there are more cheeps created by me and/or the user i follow, than the 32 page displayed on the page,
there must appear multiple pages in the button, on whichI can click.

**Comment by Faberen** [comment]
Having issues reproducing this bug, I have followed Jacqueline and my private timeline shows 12 pages which is the expected behavior?

**Comment by SkarpKat** [comment]
> Having issues reproducing this bug, I have followed Jacqueline and my private timeline shows 12 pages which is the expected behavior?

It seems the problem is the buttons in the bottom when on page 1
![image](https://github.com/ITU-BDSA23-GROUP4/Chirp/assets/143702901/cb3fd397-1111-41c5-b26e-d6a9ffe71de1)
</br>
When going to page 2 on above it works again
![image](https://github.com/ITU-BDSA23-GROUP4/Chirp/assets/143702901/970ecf2d-e019-42c5-9acd-780a3cd2f91c)

**Comment by Faberen** [comment]
This issue doesn't happen for me? I show 12 pages correctly every time. Does the bug happen when you follow perhaps yourself as well? Or do you follow other poeple than Jacqualine

**Comment by Faberen** [comment]
Found the issue, if you have written a cheep yourself the pagination only counts that one and therefore only 1 page shows up.
