### ISSUE TITLE
Write chapter on the onion diagams

### ISSUE THREAD

**Issue by Lukan707** [ITU-BDSA23-GROUP4/Chirp#261]
Dependent on the onion diagrams #260 

- Create a new file in the docs folder called text_to_onion_diagrams.md
- Write a chapter on the diagrams - remember to write about why, decisions, consequences of implementations and choices, argumentation - and not how and what is evident from the diagrams.

**Comment by annahj1006** [comment]
@Lukan707 again missing a more precise description like in issue #263

**Comment by Lukan707** [comment]
The goal of the issue is not to make an exact description of what to write, but more to give an overview over our progress with writing the report.

The bulletpoints is intended as notes, to remember when writing.

However I will try to make the points more clear in future issues, regarding the report.
