### ISSUE TITLE
Write chapter on the UML diagram

### ISSUE THREAD

**Issue by Lukan707** [ITU-BDSA23-GROUP4/Chirp#263]
Dependent on the UML diagrams #262 

- Create a file in the docs folder called UML_diagrams.md
- Write a chapter on the diagrams - remember to write about why, decisions, consequences of implementations and choices, argumentation - and not how and what is evident from the diagrams.

**Comment by annahj1006** [comment]
What do you mean about why, decisions and consequensens @Lukan707 ? This doesn't really give a great starting point.

What do you mean by "why"? Why what? Why did we draw it like we did? Why did we what?

Which decisions? Implementation decisions? Drawing decisions? I need a direction, i don't see anything fitting in that paragraph. 

Again what do you mean about consequences? Do you want me to mention our halfhearted like implementation here? Or how we are deleting them? I feel like this should be somewhere else, than in what our architecture is, unless you're thinking about the consequences of an onion architecture in itself??

The last part i don't completely understand, "not how and what is evident from the diagrams"? I think i need an explanation.

**Comment by Lukan707** [comment]
>What do you mean by "why"? Why what? Why did we draw it like we did? Why did we what?
>
>Which decisions? Implementation decisions? Drawing decisions? I need a direction, i don't see anything fitting in that paragraph.

Yes. The "why" is our choices in implementations, we did we choose the implementation, what is the alternatives, what impact does our choice have over the program and functionality.

So to further explain: By which arguments did we choose the current solution. What alternatives are there, are they better? Why are they better? Why did we not choose them anyway? Or are they not as good? Why are they not so good? etc.

I am only mentioning this, because this is the feedback, Niels and I got form our UI report.

>Again what do you mean about consequences? Do you want me to mention our halfhearted like implementation here? Or how we are deleting them? I feel like this should be somewhere else, than in what our architecture is, unless you're thinking about the consequences of an onion architecture in itself??

Well yes, as an example, if it comes naturally op from the diagrams. If it is not something that is clear, or can be read of the UML diagram, well this is not where we should discuss, but then we should discuss it in the context were it appears.

Also, consequences may be a bad word choice. Impact might be better. It is not only the bad effects, but yeah, like is a good example. How we delete authors cheeps instead of anonymizing the cheeps is another example.

>The last part i don't completely understand, "not how and what is evident from the diagrams"? I think i need an explanation.

So what I mean is: The text should not just be a text version of the UML diagram. so what we should not write is "The class something interacts with the interface somethingelse, which is implemented by the class somthing third", but instead "the interface offers maintainability, such that methods can be changed, without changing the way other components interacts with the methods". Just as an example.

I hope this clears up what I means :)

**Comment by annahj1006** [comment]
> > What do you mean by "why"? Why what? Why did we draw it like we did? Why did we what?
> > Which decisions? Implementation decisions? Drawing decisions? I need a direction, i don't see anything fitting in that paragraph.
> 
> Yes. The "why" is our choices in implementations, we did we choose the implementation, what is the alternatives, what impact does our choice have over the program and functionality.
> 
> So to further explain: By which arguments did we choose the current solution. What alternatives are there, are they better? Why are they better? Why did we not choose them anyway? Or are they not as good? Why are they not so good? etc.
> 
> I am only mentioning this, because this is the feedback, Niels and I got form our UI report.
> 
> > Again what do you mean about consequences? Do you want me to mention our halfhearted like implementation here? Or how we are deleting them? I feel like this should be somewhere else, than in what our architecture is, unless you're thinking about the consequences of an onion architecture in itself??
> 
> Well yes, as an example, if it comes naturally op from the diagrams. If it is not something that is clear, or can be read of the UML diagram, well this is not where we should discuss, but then we should discuss it in the context were it appears.
> 
> Also, consequences may be a bad word choice. Impact might be better. It is not only the bad effects, but yeah, like is a good example. How we delete authors cheeps instead of anonymizing the cheeps is another example.
> 
> > The last part i don't completely understand, "not how and what is evident from the diagrams"? I think i need an explanation.
> 
> So what I mean is: The text should not just be a text version of the UML diagram. so what we should not write is "The class something interacts with the interface somethingelse, which is implemented by the class somthing third", but instead "the interface offers maintainability, such that methods can be changed, without changing the way other components interacts with the methods". Just as an example.
> 
> I hope this clears up what I means :)


With the why - it was said directly in the project description that we were to implement it with the onion architecture, so there is no why? I mean we could mention what other architectures there is, but that wouldn't make sense for our report that should be coherrent with the application.

With the consiquences - I can mention our choices with deleting the users information, but i don't think anything else would fit here, since the section is about the architecture.

Last part - Yes makes sense, i was gonna do that anyway :))

**Comment by Lukan707** [comment]
> > > What do you mean by "why"? Why what? Why did we draw it like we did? Why did we what?
> > > Which decisions? Implementation decisions? Drawing decisions? I need a direction, i don't see anything fitting in that paragraph.
> > 
> > 
> > Yes. The "why" is our choices in implementations, we did we choose the implementation, what is the alternatives, what impact does our choice have over the program and functionality.
> > So to further explain: By which arguments did we choose the current solution. What alternatives are there, are they better? Why are they better? Why did we not choose them anyway? Or are they not as good? Why are they not so good? etc.
> > I am only mentioning this, because this is the feedback, Niels and I got form our UI report.
> > > Again what do you mean about consequences? Do you want me to mention our halfhearted like implementation here? Or how we are deleting them? I feel like this should be somewhere else, than in what our architecture is, unless you're thinking about the consequences of an onion architecture in itself??
> > 
> > 
> > Well yes, as an example, if it comes naturally op from the diagrams. If it is not something that is clear, or can be read of the UML diagram, well this is not where we should discuss, but then we should discuss it in the context were it appears.
> > Also, consequences may be a bad word choice. Impact might be better. It is not only the bad effects, but yeah, like is a good example. How we delete authors cheeps instead of anonymizing the cheeps is another example.
> > > The last part i don't completely understand, "not how and what is evident from the diagrams"? I think i need an explanation.
> > 
> > 
> > So what I mean is: The text should not just be a text version of the UML diagram. so what we should not write is "The class something interacts with the interface somethingelse, which is implemented by the class somthing third", but instead "the interface offers maintainability, such that methods can be changed, without changing the way other components interacts with the methods". Just as an example.
> > I hope this clears up what I means :)
> 
> With the why - it was said directly in the project description that we were to implement it with the onion architecture, so there is no why? I mean we could mention what other architectures there is, but that wouldn't make sense for our report that should be coherrent with the application.

No but they why is then, what are the reason to use onion architechture (also in general). 
There is a reason why we have been told to use it. In other words, we need to explain how we benefit from it, what positivie impact (this is what I mean by consequences as well, altough impact is a better word for it) does it have. 
And perphaps we might mention how it can be retrictive, or what alternatives there are (for an example three layer architechture). However, I only believe we should mention this, if comes up natural, and not force the mentioning of alternatives.

> With the consiquences - I can mention our choices with deleting the users information, but i don't think anything else would fit here, since the section is about the architecture.

That is a good example of impacts (consequences, however, this might not be the relevant place for that discussion, but we should definetly include it in the report somewhere appropiate. 😃 

> Last part - Yes makes sense, i was gonna do that anyway :))

Nice 😸
