### ISSUE TITLE
There are missing tests in AuthorRepository 

### ISSUE THREAD

**Issue by AlbinoLoaf** [ITU-BDSA23-GROUP4/Chirp#292]
## Precise description of what to do and evt. time estimate
Some public methods lack matching tests both negation and confirmation tests

## Acceptance criteria (testeable)
- [x] AddAuthor 
- [x] DoesAuthorExist

**Comment by annahj1006** [comment]
AddAuthor can only be tested for if it does add the author, since we do nothing if the author already exists.
