### ISSUE TITLE
Cheep repo lacks tests

### ISSUE THREAD

**Issue by AlbinoLoaf** [ITU-BDSA23-GROUP4/Chirp#293]
## Precise description of what to do and evt. time estimate
There lacks both negation and confirmation tests.

## Acceptance criteria (testeable)

- [x] AddCheep 
- [x] GetCheeps
- [x] GetCheepsFromAuthor
- [x] GetCountOfAllCheeps
- [x] GetCountOfAllCheepFromAuthor
- [x] CombineCheepsAndFollowerCheeps
- [x] GetCountOfAllCheepsFromCombinedAuthor

**Comment by SkarpKat** [comment]
AddCheep has been removed
