### ISSUE TITLE
As a developer I want to refactor the database to a File-based SQLite database

### ISSUE THREAD

**Issue by Faberen** [ITU-BDSA23-GROUP4/Chirp#32]
### Acceptance Criteria:

- Retire CSV database completely
- Encapsulate all database related code, i.e., establishing of connections, access of data, etc. into its own "wrapper" class called DBFacade.cs.
- Modify the code in the method GetCheeps() in CheepService.cs so that it executes an SQL query against the SQLite database.

**Comment by Lukan707** [comment]
This has been resolved and merged into developmetn
