### ISSUE TITLE
As developer I want to implement pagination of cheeps. 

### ISSUE THREAD

**Issue by Faberen** [ITU-BDSA23-GROUP4/Chirp#35]
### Acceptance criteria:

- Modify the Razor Pages of the public and private timelines so that you read query parameters that are provided via the URL that specify which page a client wants to receive. 
- Implement /Page1 that redirects to page 1 of all the cheeps ie, for all available pages,
- Implement /Author that redirects to a specific users cheeps ie, Helges cheeps, rasmus's cheeps and so on

**Comment by Lukan707** [comment]
This has now been resolved and pushed into main.
