### ISSUE TITLE
As a developer i want to refacter the Page system into the cshtlm.cs 

### ISSUE THREAD

**Issue by AlbinoLoaf** [ITU-BDSA23-GROUP4/Chirp#36]
We do this to avoid the main page and subpages in sharing page count as they do know causing issues

Currently they share the resource causing a non-invasive bug

**Comment by Lukan707** [comment]
The bug still occurs, however the solution is not the right one. Look in the README_PROJECT.md on the course github, where the solution is described (pagination).

**Comment by Lukan707** [comment]
THIS IS A DUPLICATE. SEE [Issue #35](../issues/35)

The bug still occurs, however the solution is not the right one. Look in the README_PROJECT.md on the course github, where the solution is described (pagination).
