### ISSUE TITLE
As a user I want ot be able to view a specific page number

### ISSUE THREAD

**Issue by Faberen** [ITU-BDSA23-GROUP4/Chirp#41]
Problem area: Currently the razor pages allow us to increment and decrement by one with the buttons. Although since we now have over 600 cheeps being able to go back to page 1 immediately might be worth implementing 

Success criteria:

- Implement queries that show a specific pages cheeps instead of filtering it out in c# code. Look at 1.b for further reference.

**Comment by Lukan707** [comment]
This have been resolved, and pushed into main.
