### ISSUE TITLE
As a developer, I want to refactor the csv file handling to a seperate project, in such a way that the database package can be used generically.

### ISSUE THREAD

**Issue by Lukan707** [ITU-BDSA23-GROUP4/Chirp#5]
As a developer, I want to refactor the csv file handling to a seperate project, in such a way that the database package can be used generically, and that the implementation of the database project can be changed, without having an affect and creating a neeed to change the rest of the application.
In less word, create less coupling.

Create a new project to contain a database (csv handling) and move the refactored code into a class, which can't be a parent of subclass, and should implement an interface, which other application can instantiate.

Acceptance criteria:
* All database handling should be inside it's own seperate folder. 
* It should be possible to use another instance of the databaseproject, to handle other data in another application (project) than Chirp.
* The project should have an interface and a class implementing that interface. 
* It should not be possible to create a subclass of the class, implementing the interface.
* The Chirp application should only contian code for retrieving command-line arguments and printing output (should only contiain the UI of the application).

Dependency (theese need to be finished first):
#1 
#2

**Comment by SkarpKat** [comment]
Issue has been resolved and merged.
