### ISSUE TITLE
As a developer i want to know more about the dbContext script that are used when creating a database model script

### ISSUE THREAD

**Issue by annahj1006** [ITU-BDSA23-GROUP4/Chirp#50]
The normal look for a model context class (based on the torturial - and without the properties) is this:

                public class BloggingContext : DbContext
                {
                public BloggingContext()
                    {
                        var folder = Environment.SpecialFolder.LocalApplicationData;
                        var path = Environment.GetFolderPath(folder);
                        DbPath = System.IO.Path.Join(path, "blogging.db");
                    }
                
                    // The following configures EF to create a Sqlite database file in the
                    // special "local" folder for your platform.
                    protected override void OnConfiguring(DbContextOptionsBuilder options)
                        => options.UseSqlite($"Data Source={DbPath}");
                }

Our context looks like this:

                public class ChirpDBContext : DbContext
                {
                    public ChirpDBContext()
                    {
                        var folder = Environment.SpecialFolder.LocalApplicationData;
                        var path = Environment.GetFolderPath(folder);
                        DbPath = System.IO.Path.Join(path, "chirp.db");
                    }
                    protected override void OnModelCreating(ModelBuilder modelBuilder)
                    {
                        //relationships and constraints
                    }
                }

What exactly should relationsships be, and what is possible by using the Microsoft.EntityFrameworkCore package?

**Comment by Lukan707** [comment]
Maybe @SkarpKat can answer this now?

**Comment by SkarpKat** [comment]
> Maybe @SkarpKat can answer this now?

I can show and talk about this tomorrow if people are interested.
