### ISSUE TITLE
Change implementation, so that we only request up to 32 cheeps from Database, and with an offset dependent on the page.

### ISSUE THREAD

**Issue by Lukan707** [ITU-BDSA23-GROUP4/Chirp#57]
## User story
As a user, I want quick responses from the webpage. To achieve this, minimize the amount of data, sent from the database to the API.

## Precise description
Change the implementation of GetCheeps and GetCheepsAuthor in CheepRepository to only request 32 cheeps (or less) from the database, instead of a full list. Consider the implication if there are millions of cheeps.
The cheeps should be requested with an offset, dependent on the page, so the correct range of cheeps is returned.

Research how to achieve this, and post the answer in the comment section below, before implimenting it.

## Acceptance criteria
- The CheepRepository should only request a maximum of 32 cheeps from the Database.
- The correct range of cheeps should be requested. 
I.e. if cheeps is requested for page 1, request cheeps 0-31.
If the page is 2, request cheeps 32-63. And so on.

# Edit

**Comment by AlbinoLoaf** [comment]
## Tests Made

Check32Cheeps
CheepsOnPage0IsTheSameAsPage1
CheepsOnPage1IsNotTheSameAsPage2

## Missing Tests  
here is a list of missing tests and a short description 
### TestPage2Has32Cheeps
- Check that the second public timeline page also has exactly 32 cheeps 
- Check this as it ensures proper indexing no matter the get method 
### AutherHas32Cheeps 
- Cheek that the Author has 32 cheeps per page,
- It is an alternate method from the public view and thus requires full testing
- Do it for both Pages 1 and 2 
### AutherPage1andRootAreEqual
- Is /Author/ the same as author/?page=1
### TestOrderCheepbyDate 
- check that the order of the cheeps are in order according to the DateString to ensure the content for page 1 comes before the content on page 2
