### ISSUE TITLE
Research and understand the "transport information to your views" part 1.c week 6

### ISSUE THREAD

**Issue by AlbinoLoaf** [ITU-BDSA23-GROUP4/Chirp#64]
## Understand what the requirement is
We currently are not sure if the data transported with the DTO, our page does represent the information but we do not have explicit view
##Acceptance criteria (testeable)
- Knowing if we should do something 
# Notes:
Might evolve into a development issue.

**Comment by Lukan707** [comment]
When asking Helge, we got the following response on how to view 'views'.

The way we should view 'views', is to view the cshtml files, as our 'views', which the layer between the user and the DTO, which all 'views' should be using
