### ISSUE TITLE
Use in-memory SQLite database for testing

### ISSUE THREAD

**Issue by annahj1006** [ITU-BDSA23-GROUP4/Chirp#67]
## User story
As a developer we want to ensure, that we do not affect or corrupt data in the production database when we perform our test. Neither do we want to have our test fail, because the porduction or other test affects the data we test for.

## Description
Change the test to use the in-memory SQLite database, instead of the production database.
This is to avoid to affect or corrupt data in the production database when testing.
Also we do not want a testcase to fail, due to deleted or altered data.
Lastly we want a new in-memory database to be created for each test, as one test aletering the data in the database, can affect or corrupt the result of another test.

## Acceptance criteria

- [x] - Each test should cerate a new in-memory database. 
- [x] - Test for a database being empty when created.
- [x] - Test that the prodcution database is not affected, after data is inserted into a in-memory test.

**Comment by AlbinoLoaf** [comment]
describe what needs to be done

**Comment by AlbinoLoaf** [comment]
Make it possible to test with an In-memory database for tests and reflector tests


## tests 
Put something into the in-memory database and check it is not the Main DB
