### ISSUE TITLE
Change nullable values to required where appropiate.

### ISSUE THREAD

**Issue by Lukan707** [ITU-BDSA23-GROUP4/Chirp#68]
## User story
As a developer I want to ensure that the variables in the context that need to be required are marked as `required` to ensure that these fields are filled. 

## Description
Find the places in the code, where regarding to data integrity and out data model, it is appropiate to change nullable variables to required variables.
When you find the variables that needs to be change do change them

## Acceptance criteria (testeable)
- The program can still be executed and the EF Core commands <br> Stand in Chirp folder `dotnet ef migrations add --project src/Chirp.Razor/Chirp.Razor.csproj --startup-project src/Chirp.Infrastructure/Chirp.Infrastructure.csproj`

**Comment by SkarpKat** [comment]
This may already be fixed since most of the variables in the Author.cs and Cheep.cs are already `required`.
