### ISSUE TITLE
As a developer I want to write unit test to the new methods that are created in the repository, IE Find Author by name and email and create author

### ISSUE THREAD

**Issue by annahj1006** [ITU-BDSA23-GROUP4/Chirp#69]
## Description 
Now, that you have decoupled your data persistence code properly from your application, augment your test suite from last time.

After: #83 
After: #75 

Implement a set of unit tests for suitable functionality, e.g., all of the repository methods from the task above, data conversion, etc.

## Acceptance Criteria:

    Write a unit test that finds an author by email
    ------"------- that finds author by name
    ------"------- that doesn't find a user when giving a wrong mail
    ------"------- that doesn't find a user when giving a wrong name
    ------"------- that creates an author successfully

**Comment by AlbinoLoaf** [comment]
After #75

**Comment by Faberen** [comment]
Acceptance Criteria:

- Write a unit test that finds an author by email
- ------"------- that finds author by name
- ------"------- that doesn't find a user when giving a wrong mail
- ------"------- that doesn't find a user when giving a wrong name
- ------"------- that creates an author successfully

**Comment by Lukan707** [comment]
Dependent on #67
