### ISSUE TITLE
Extend the repository for Author

### ISSUE THREAD

**Issue by annahj1006** [ITU-BDSA23-GROUP4/Chirp#75]
## User Story
As a fellow developer, I want to know what methods i can use through the interface and in the repository,

## Description
Add a few methods to enable more functionality, They should be public and be in the interface. 
### Method 1 
Find Author by name
- A search query to the database, Make sure to implement CQS so that if it is only a query (retrieving data)
### Method 2
Find Author by Email
- A search query to the database, Make sure to implemented CQS so that it is only a query (retrieveing data)
### Method 3 
Create Author
- A command to insert data to the database. Make sure to implement a CQS so that it is only a command (inserting data)

## Acceptance Criteria 
- Implemented unit tests #69 

## Edit
This issue is dependent on #84

**Comment by AlbinoLoaf** [comment]
Split up into more issues with acceptance criteria and descriptions
