### ISSUE TITLE
Change database from singleton pattern to a scoped pattern.

### ISSUE THREAD

**Issue by Lukan707** [ITU-BDSA23-GROUP4/Chirp#78]
## User story
As a user, I do not want to experience data getting lost or altered in unexpected ways.

## Description
Change the implementation of the database from a singleton pattern into a scoped pattern.
This is to ensure concurrency, if two users tries to update the same data at the same time.

## Acceptance criteria
- For each request a new instance of the database should be created.
- The database instance should exists for the whole each request

**Comment by AlbinoLoaf** [comment]
What kind of user are you

**Comment by Lukan707** [comment]
This is completed by @TheSharpCat on branch Restricted cheep length and in memory testing
