### ISSUE TITLE
Extend the repository for Cheep

### ISSUE THREAD

**Issue by annahj1006** [ITU-BDSA23-GROUP4/Chirp#83]
## User Story
As a developer I want to extend the CheepRepository to support new exposed methodes

## Description 
Expose methods in your repositories (OBS: that includes the respective interfaces) that enable to:

If not implemented already, retrieve cheeps for a certain page.

If not implemented already, retrieve cheeps for a certain page that are written by a certain Author who is identified by name

Create a new cheep. Note, that might mean to also create a respective author if she does not exist yet in Chirp!.

**Comment by SkarpKat** [comment]
This is already implemented and you can find this in the CheepRepository.cs. If anything the only thing that can be changed is to make a AuthorRepository.cs.
